name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  file_saver: ^0.2.12
  csv: ^6.0.0
  fl_chart: ^0.68.0
  scidart: ^0.0.2-dev.12
  # Already possesed by internal website
  resizable_widget: ^1.0.5
  pluto_grid:
    git: https://github.com/bosskmk/pluto_grid.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
